"""Added price field

Revision ID: 718ff685c9da
Revises: c789fb7be98a
Create Date: 2020-02-16 18:38:04.041826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718ff685c9da'
down_revision = 'c789fb7be98a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('price', sa.Float(), nullable=False, server_default="0.0"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'price')
    # ### end Alembic commands ###
