"""Create tables

Revision ID: 93d4bc69a0ae
Revises: 2d6c64009825
Create Date: 2019-08-11 21:17:17.983700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93d4bc69a0ae'
down_revision = '2d6c64009825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('dish_type', sa.String(length=15), nullable=False),
    sa.Column('ingredients', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reviews',
    sa.Column('rev_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rev_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('dishes')
    # ### end Alembic commands ###
